Feat/typescript init errors fix
AckeeCZ/redux-utils pull request #34
Opened 2020-12-01 16:20 UTC by baierjak

IT IS ALL ABOUT THE TYPESCRIPT!

It is a bigger one, but most of changes are renamed file extensions from .js to .ts

new babel preset for building Typescript
new package.json scripts for Typescript
tsconfig, jest.config and tslint config added

All files has tslint disable and also typescript disabled (nocheck) because of a lot of files
I will handle them separately. I have started with one typescript Interface in constanst/index.js

2020-12-03 08:55 UTC, Tomas2D approved these changes

2020-12-06 16:51 UTC, horaklukas approved these changes

2020-12-06 16:51 UTC, horaklukas commented on src/utilities/apiRequestType/apiRequestType.ts
> +import { RequestTypeParams } from '../../constants';
`RequestTypeParams` is not related to constants anyhow, I would rather put it just inside this file

2020-12-06 16:51 UTC, horaklukas commented on tsconfig.types.json
> +        "outDir": "es"
are `d.ts` emitted also into the `lib` or just `es` dir?

2021-03-01 11:29 UTC, baierjak commented on tsconfig.types.json
> +        "outDir": "es"
I simply dont know - how it should be?
Do I need `d.ts` files here at all?
I am a newbie at Typescript but I dont see any purpose for use them here.

2021-03-01 11:29 UTC, baierjak commented on src/utilities/apiRequestType/apiRequestType.ts
> +import { RequestTypeParams } from '../../constants';
yes thats right

2021-03-01 11:39 UTC, baierjak commented on tsconfig.types.json
> +        "outDir": "es"
For now the `d.ts` files are generated only in `es` dir

![image](https://user-images.githubusercontent.com/7579303/109492351-22557200-7a8b-11eb-951d-d8849a032403.png)

2021-03-02 18:32 UTC, baierjak commented on tsconfig.types.json
> +        "outDir": "es"
any additional answer guys here? :)

2021-03-02 19:51 UTC, horaklukas commented on tsconfig.types.json
> +        "outDir": "es"
I checked other packages and d.ts files are also emitted only into the one file so let's keep it until we find out it's wrong 🙂

2021-03-02 20:07 UTC, jancama2 requested changes

2021-03-02 20:07 UTC, jancama2 commented on package.json
>          "@babel/preset-env": "7.x",
Not used here?

2021-03-02 20:07 UTC, jancama2 commented on package.json
>          "@babel/preset-modules": "0.x",
Not used here?

2021-03-02 20:07 UTC, jancama2 commented on package.json
> +        "tslint-config-ackee": "^0.3.0",
TSlint is deprecated in favor of ESlint so pls upgrade all the eslint packages and use it :)

2021-03-02 20:07 UTC, jancama2 commented on package.json
>          "eslint-import-resolver-webpack": "0.x",
No webpack used in the project

2021-03-02 20:07 UTC, jancama2 commented on package.json
>          "webpack": "4.x"
No webpack used in the project

2021-03-02 20:07 UTC, jancama2 commented on package.json
> +        "prettier": "prettier --config ./prettier.config.ts --write './src/**/*.ts'",
Do we need a command for it? It is done by husky.

2021-03-02 20:07 UTC, jancama2 commented on webpack.config.js
>  module.exports = {
This file is unnecessary as we don't use webpack in the project.

2021-03-03 11:49 UTC, baierjak commented on package.json
> +        "tslint-config-ackee": "^0.3.0",
yes, I will let this as it is now - and after team meeting this week I will change it - when i will have more information about it :)

2021-03-03 11:50 UTC, baierjak commented on package.json
> +        "prettier": "prettier --config ./prettier.config.ts --write './src/**/*.ts'",
maybe not - husky even doesnt use this command :) cool

2021-03-03 11:50 UTC, baierjak commented on webpack.config.js
>  module.exports = {
👍

2021-03-03 11:55 UTC, baierjak commented on package.json
>          "@babel/preset-modules": "0.x",
babel uses this, cant delete it :)

2021-03-03 11:58 UTC, baierjak commented on package.json
>          "@babel/preset-env": "7.x",
babel uses this, cant delete it :) for browslist ... 
https://babeljs.io/docs/en/babel-preset-env

2021-03-03 11:58 UTC, baierjak commented on package.json
>          "eslint-import-resolver-webpack": "0.x",
yes

2021-03-03 11:58 UTC, baierjak commented on package.json
>          "webpack": "4.x"
yes

2021-03-03 11:59 UTC, merged

2021-03-03 12:24 UTC, jancama2 commented on package.json
>          "@babel/preset-env": "7.x",
I cant see it anywhere used tho :)

2021-03-03 12:28 UTC, jancama2 commented on package.json
>          "@babel/preset-env": "7.x",
right, missed it in the config, srry

2021-03-03 12:28 UTC, jancama2 commented on package.json
>          "@babel/preset-modules": "0.x",
right, missed it in the config, srry