Feat/ts all files
AckeeCZ/redux-utils pull request #37
Opened 2021-03-02 18:31 UTC by baierjak

based on #36 

All JS files left written to Typescript.

Sometimes I used `any` or `object` because I didnt know how to do it right, I definitely will accept some feedback about it.

There is one file which still has TS-nocheck and TODO - because I cant fix that TS issue there and didnt want to spent all day with that ))

🎉

2021-03-02 19:44 UTC, Tomas2D requested changes

2021-03-02 19:44 UTC, Tomas2D commented on src/actions/apiRequest/apiRequestActions.ts
>   * @param {Object} [options] for creating action creators
We could propably remove JSDoc as we are moving to typescript.

2021-03-02 19:44 UTC, Tomas2D commented on src/actions/apiRequest/templates.ts
> +};
💡 Use generic types for better whispering.

```
const list = {
    REQUEST: (type: string) => (params: object = {}) => ({
        type,
        payload: params,
    }),
    SUCCESS: (type: string) => <T extends any>(payload: T, meta: object = {}) => ({ type, meta, payload }),
    FAILURE: (type: string) => <T extends any>(error: T) => ({ type, error }),
    CANCEL: (type: string) => () => ({ type }),
    RESET: (type: string) => () => ({ type }),
};
```

2021-03-02 19:44 UTC, Tomas2D commented on src/actions/apiRequest/templates.ts
> +};
Same here.

2021-03-02 19:44 UTC, Tomas2D commented on src/config/reducers/containerReducer.ts
> +    const options: any = Object.freeze({
This will object for sure. Any is misleading and redundant.

2021-03-02 19:44 UTC, Tomas2D commented on src/config/reducers/containerReducer.ts
> +    const selectors: any = Object.freeze({
Same here.

2021-03-02 19:44 UTC, Tomas2D commented on src/reducers/reset/container/factoryReducer.ts
> +const addItemIdToActionTypes = (dest: any = {}, itemId: string = '', actionTypes: string[] = []) => {
Dest should not be propably any, because on line 17 you make access to this variable via index operator.

```
type ObjectLike = { [prop: string]: any };

const addItemIdToActionTypes = (dest: ObjectLike = {}, itemId: string = '', actionTypes: string[] = []) => {
    ...
}
```

or if it should only and only object, simply use this

```
const addItemIdToActionTypes = (dest: object = {}, itemId: string = '', actionTypes: string[] = []) => {
    ...
}
```

2021-03-02 19:44 UTC, Tomas2D commented on src/reducers/reset/container/factoryReducer.ts
> +const createRevertedMap = (resetItems: any = {}) => {
Same here.

2021-03-02 20:30 UTC, Tomas2D commented on src/reducers/reset/container/factoryReducer.ts
> +        // TODO Fix this TS issue with any assigning to never and remove TS disable comment above
💡 This could be solved via generics.

```
type ValueOf<T> = T[keyof T];

const resetItemsToInitialState = (
    itemIds= new Set<keyof ApiReducerState>(),
    childReducer: (...args) => ValueOf<ApiReducerState>,
    itemInitialState: ApiReducerState,
) => {
    const newState: ApiReducerState = {};
    const mockAction: Action = {};

    for (const itemId of itemIds.values()) {
        (newState[itemId] as ValueOf<ApiReducerState>) = childReducer(undefined, mockAction, itemInitialState);
    }

    return newState;
};
```

2021-03-03 12:46 UTC, baierjak commented on src/reducers/reset/container/factoryReducer.ts
> +        // TODO Fix this TS issue with any assigning to never and remove TS disable comment above
<3 <3 <3

2021-03-03 13:03 UTC, baierjak commented on src/actions/apiRequest/apiRequestActions.ts
>   * @param {Object} [options] for creating action creators
definitely

2021-03-03 13:03 UTC, baierjak commented on package.json
> +        "src/*.{ts,json,scss,less,css,md}": [
yes, good point

2021-03-03 13:03 UTC, jancama2 requested changes

2021-03-03 13:03 UTC, jancama2 commented on src/actions/apiRequest/templates.ts
> +    REQUEST: (type: string) => (params = {}) => ({
`REQUEST` is not a constant:
```
const lists = {
   request: ...,
   success: ...,
   ...,
}
```
Btw we started to use `import { createAction } from '@reduxjs/toolkit` so pls could you integrate it?

```
const list = {
   request: (type: string) => createAction(type);
   success: (type: string) => createAction(type, (payload, meta) => ({ meta, payload }),
   failure: (type: string) => createAction(type, (error) => ({ error }),
   ...
}
```

2021-03-03 13:03 UTC, jancama2 commented on src/actions/apiRequest/templates.ts
> +};
I would use the generics too :))

2021-03-03 13:09 UTC, baierjak commented on src/actions/apiRequest/templates.ts
> +};
thats really cool!

2021-03-03 13:09 UTC, baierjak commented on src/actions/apiRequest/templates.ts
> +};
done

2021-03-03 13:11 UTC, baierjak commented on src/config/reducers/containerReducer.ts
> +    const options: any = Object.freeze({
right

2021-03-03 13:13 UTC, baierjak commented on src/reducers/reset/container/factoryReducer.ts
> +const addItemIdToActionTypes = (dest: any = {}, itemId: string = '', actionTypes: string[] = []) => {
👍

2021-03-03 13:30 UTC, baierjak commented on src/actions/apiRequest/templates.ts
> +    REQUEST: (type: string) => (params = {}) => ({
What does it mean `We started to use ....` - we should discuss it at team meeting because I am not sure on what projects it is used by now.

2021-03-03 13:32 UTC, baierjak commented on src/actions/apiRequest/templates.ts
> +    REQUEST: (type: string) => (params = {}) => ({
and both are not relevant to this PR

feel free to contribute ! 👯

2021-03-03 13:35 UTC, jancama2 approved these changes

2021-03-03 13:39 UTC, baierjak commented
@Tomas2D 🚀

2021-03-04 16:47 UTC, Tomas2D commented on src/actions/apiRequest/templates.ts
> +};
`<T extends any>`, `any` is unnecessary here. Can be removed.

2021-03-04 17:04 UTC, Tomas2D commented on src/config/reducers/basicApiReducer.ts
> +export default function configurateBasicApiReducer(customConfigure?: any) {
I thought `customConfigure` should contain the same keys as `ApiReducerState`. Can you type it?

What about this?

```
type ExtendedConfig = object & ApiReducerState;

interface MergeConflictArgs {
    initialState: ApiReducerState;
}

export default function configurateBasicApiReducer(customConfigure: (initialState: MergeConflictArgs) => ExtendedConfig): ExtendedConfig {
    return mergeConfigs({ initialState }, customConfigure);
}
```

2021-03-04 17:54 UTC, Tomas2D approved these changes

2021-03-04 17:58 UTC, merged

2021-03-05 17:04 UTC, baierjak commented on src/config/reducers/basicApiReducer.ts
> +export default function configurateBasicApiReducer(customConfigure?: any) {
What does it exactly mean? `customConfigure: (initialState: MergeConflictArgs) => ExtendedConfig` ? 
It seems to me like `customConfigure` type is a function - but it should be object which includes the initial state right?

2021-03-05 17:13 UTC, Tomas2D commented on src/config/reducers/basicApiReducer.ts
> +export default function configurateBasicApiReducer(customConfigure?: any) {
`customConfigure: (initialState: MergeConflictArgs) => ExtendedConfig` is `function` which takes one parameter (`object`) which has one property called `initialState` of type `ApiReducerState` and must return object which extends the `ApiReducerState`.

`configurateBasicApiReducer(({ initialState }) => { ...initialState, inProgress: true, randomProp: 100 });`